/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DataPersonal.java
 *
 * Created on Jun 11, 2013, 1:33:52 AM
 */
package Desktop;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
/**
 *
 * @author Izani Note-PC1
 */
public class DataPersonal extends javax.swing.JFrame {

    /** Creates new form DataPersonal */
    public DataPersonal() {
        initComponents();
        setTitle("Laporan Data Personal Administrasi Data PKM-UI");
        bukapasien();
        
    }
    
    public void bukapasien(){
        DefaultTableModel MapTablePasien = new DefaultTableModel();
        MapTablePasien.addColumn("Kode");
        MapTablePasien.addColumn("Nama");
        MapTablePasien.addColumn("Jenis Kelamin");
        MapTablePasien.addColumn("Identitas");  
        MapTablePasien.addColumn("Tanggal Lahir");  
        MapTablePasien.addColumn("Fakultas");
        MapTablePasien.addColumn("No Telepon");
        MapTablePasien.addColumn("Alamat");
        
        try {
            koneksi objkoneksi = new koneksi();
            Connection con = (Connection) koneksi.bukakoneksi();
            String bukadata = "select * from pasien";
            Statement stat = (Statement) con.createStatement();
            ResultSet rs = stat.executeQuery(bukadata);
            while (rs.next()){
                MapTablePasien.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8)});
            }
            table_pasien.setModel(MapTablePasien);
        } catch (Exception e) {
            
        }
    }
    
    
    public void cari_pasien(){
        DefaultTableModel MapTablePasien = new DefaultTableModel();
        MapTablePasien.addColumn("Kode");
        MapTablePasien.addColumn("Nama");
        MapTablePasien.addColumn("Jenis Kelamin");
        MapTablePasien.addColumn("Identitas");  
        MapTablePasien.addColumn("Tanggal Lahir");  
        MapTablePasien.addColumn("Fakultas");
        MapTablePasien.addColumn("No Telepon");
        MapTablePasien.addColumn("Alamat");
        
        try {
            String metode = (String) combo_pasien.getSelectedItem();
        String kata_kunci = null;
        
        if (metode == "Kode Pasien"){
            kata_kunci = "kode";
        } else if (metode == "Nama") {
            kata_kunci = "nama";
        } else if (metode == "Identitas") {
            kata_kunci = "nim";
        } else if (metode == "Tanggal Lahir") {
            kata_kunci = "tanggal_lahir";
        } else if (metode == "Fakultas") {
            kata_kunci = "fakultas";
        } else if (metode == "Alamat") {
            kata_kunci = "alamat";
        }
            
            
            String query = "select * from pasien where " + kata_kunci + " like '%" + txt_kode_pasien.getText() + "%'";
            koneksi objkoneksi = new koneksi();
            Connection con = (Connection) koneksi.bukakoneksi();
            Statement stat = (Statement) con.createStatement();
            ResultSet rs = stat.executeQuery(query);
            while (rs.next()) {
                MapTablePasien.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8)});
            }
            table_pasien.setModel(MapTablePasien);
        } catch (Exception e) {
            
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        combo_pasien = new javax.swing.JComboBox();
        txt_kode_pasien = new javax.swing.JTextField();
        cari_pasien = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_pasien = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Personal"));

        jLabel11.setText("Tampilkan berdasarkan :");

        combo_pasien.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kode Pasien", "Nama", "Identitas", "Tanggal Lahir", "Fakultas", "Alamat" }));

        cari_pasien.setText("Tampilkan");
        cari_pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_pasienActionPerformed(evt);
            }
        });

        table_pasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama", "Jenis Kelamin", "Identitas", "Tanggal Lahir", "Fakultas", "No Telepon", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_pasien);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_kode_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cari_pasien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(combo_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kode_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari_pasien)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cari_pasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_pasienActionPerformed
// TODO add your handling code here:
    String kode = txt_kode_pasien.getText();
    
    if (kode.equals("") || kode.length() < 1) {
        JOptionPane.showMessageDialog(null, "Silahkan isi kata kunci yang akan dicari!", "Message",
                JOptionPane.INFORMATION_MESSAGE);
        txt_kode_pasien.requestFocus();
    } else {
        cari_pasien();
    }
}//GEN-LAST:event_cari_pasienActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    new Laporan().show();
    this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    bukapasien();
}//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DataPersonal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari_pasien;
    private javax.swing.JComboBox combo_pasien;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_pasien;
    private javax.swing.JTextField txt_kode_pasien;
    // End of variables declaration//GEN-END:variables
}
