/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DataApotek.java
 *
 * Created on Jun 11, 2013, 8:00:50 AM
 */
package Desktop;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;

/**
 *
 * @author Izani Note-PC1
 */
public class DataApotek extends javax.swing.JFrame {

    /** Creates new form DataApotek */
    public DataApotek() {
        initComponents();
        setTitle("Laporan Data Periksa Administrasi Data PKM-UI");
        bukaperiksa();
    }
  
    public void bukaperiksa(){
        DefaultTableModel MapTablePeriksa = new DefaultTableModel();
        MapTablePeriksa.addColumn("Kode");
        MapTablePeriksa.addColumn("Nama");
        MapTablePeriksa.addColumn("Keluhan");
        MapTablePeriksa.addColumn("Resep");
        MapTablePeriksa.addColumn("Diagnosa");
        MapTablePeriksa.addColumn("Pemeriksa");
        MapTablePeriksa.addColumn("Apoteker");
        MapTablePeriksa.addColumn("Status");
        
        try {
            String query = "select *, nama from periksa LEFT Join pasien ON periksa.kode = pasien.kode";
            koneksi objkoneksi = new koneksi();
            Connection con = (Connection) koneksi.bukakoneksi();
            Statement stat = (Statement) con.createStatement();
            ResultSet rs = stat.executeQuery(query);
            while (rs.next()) {
                MapTablePeriksa.addRow(new Object[]{rs.getString(1),rs.getString(16), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)});
                
            }
            table_periksa.setModel(MapTablePeriksa);
        } catch (Exception e) {
            
        }
    }
    
    public void cari_periksa(){
        DefaultTableModel MapTablePeriksa = new DefaultTableModel();
        MapTablePeriksa.addColumn("Kode");
        MapTablePeriksa.addColumn("Nama");
        MapTablePeriksa.addColumn("Keluhan");
        MapTablePeriksa.addColumn("Resep");
        MapTablePeriksa.addColumn("Diagnosa");
        MapTablePeriksa.addColumn("Pemeriksa");
        MapTablePeriksa.addColumn("Apoteker");
        MapTablePeriksa.addColumn("Status");
        
        try {
            String metode = (String) combo_periksa.getSelectedItem();
        String kata_kunci = null;
        
        if (metode == "Kode Pasien"){
            kata_kunci = "kode";
        } else if (metode == "Resep") {
            kata_kunci = "resep";
        } else if (metode == "Diagnosa") {
            kata_kunci = "diagnosa";
        } else if (metode == "Pemeriksa") {
            kata_kunci = "pemeriksa";
        } else if (metode == "Apoteker") {
            kata_kunci = "apoteker";
        } else if (metode == "Status"){
            kata_kunci = "status";
        } else if (metode == "Nama"){
            kata_kunci = "nama";
        }
            
            
            String query = "select *, nama from periksa LEFT Join pasien ON periksa.kode = pasien.kode where " + kata_kunci + " like '%" + txt_kode_periksa.getText() + "%'";
            koneksi objkoneksi = new koneksi();
            Connection con = (Connection) koneksi.bukakoneksi();
            Statement stat = (Statement) con.createStatement();
            ResultSet rs = stat.executeQuery(query);
            while (rs.next()) {
                MapTablePeriksa.addRow(new Object[]{rs.getString(1),rs.getString(16), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)});
                
            }
            table_periksa.setModel(MapTablePeriksa);
        } catch (Exception e) {
            
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        combo_periksa = new javax.swing.JComboBox();
        txt_kode_periksa = new javax.swing.JTextField();
        btn_cari_periksa = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_periksa = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Periksa"));

        jLabel10.setText("Tampilkani berdasarkan :");

        combo_periksa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kode Pasien", "Nama", "Resep", "Diagnosa", "Pemeriksa", "Apoteker", "Status" }));

        btn_cari_periksa.setText("Tampilkan");
        btn_cari_periksa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cari_periksaActionPerformed(evt);
            }
        });

        table_periksa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Keluhan", "Resep", "Diagnosa", "Pemeriksa", "Apoteker", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(table_periksa);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_periksa, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_kode_periksa, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cari_periksa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(combo_periksa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kode_periksa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari_periksa)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btn_cari_periksaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_periksaActionPerformed
// TODO add your handling code here:
    String kode = txt_kode_periksa.getText();
    
    if (kode.equals("") || kode.length() < 1) {
        JOptionPane.showMessageDialog(null, "Silahkan isi kata kunci yang akan dicari!", "Message",
                JOptionPane.INFORMATION_MESSAGE);
        txt_kode_periksa.requestFocus();
    } else {
        cari_periksa();
    }
}//GEN-LAST:event_btn_cari_periksaActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    bukaperiksa();
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    new Laporan().show();
    this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataApotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataApotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataApotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataApotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DataApotek().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari_periksa;
    private javax.swing.JComboBox combo_periksa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable table_periksa;
    private javax.swing.JTextField txt_kode_periksa;
    // End of variables declaration//GEN-END:variables
}
