/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DataKunjungan.java
 *
 * Created on Jun 11, 2013, 1:38:24 AM
 */
package Desktop;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
/**
 *
 * @author Izani Note-PC1
 */
public class DataKunjungan extends javax.swing.JFrame {

    /** Creates new form DataKunjungan */
    public DataKunjungan() {
        initComponents();
        setTitle("Laporan Data Kunjungan Administrasi Data PKM-UI");
        bukakunjungan();
    }
    
    
    public void bukakunjungan(){
        DefaultTableModel MapTableKunjungan = new DefaultTableModel();
        MapTableKunjungan.addColumn("Kode");
        MapTableKunjungan.addColumn("Nama");
        MapTableKunjungan.addColumn("Tanggal");
        MapTableKunjungan.addColumn("Petugas");
        
        try {
            String query = "select *, nama from kunjungan LEFT Join pasien ON kunjungan.kode = pasien.kode";
            koneksi objkoneksi = new koneksi();
            Connection con = (Connection) koneksi.bukakoneksi();
            Statement stat = (Statement) con.createStatement();
            ResultSet rs = stat.executeQuery(query);
            while (rs.next()) {
                MapTableKunjungan.addRow(new Object[]{rs.getString(1), rs.getString(12), rs.getString(2), rs.getString(3)});
                
            }
            table_kunjungan.setModel(MapTableKunjungan);
        } catch (Exception e) {
            
        }
    }
    
   
    public void cari_kunjungan(){
        DefaultTableModel MapTableKunjungan = new DefaultTableModel();
        MapTableKunjungan.addColumn("Kode");
        MapTableKunjungan.addColumn("Nama");
        MapTableKunjungan.addColumn("Tanggal");
        MapTableKunjungan.addColumn("Petugas");
        
        try {
            String metode = (String) combo_kunjungan.getSelectedItem();
        String kata_kunci = null;
        
        if (metode == "Kode Pasien"){
            kata_kunci = "kode";
        } else if (metode == "Tanggal Kunjungan") {
            kata_kunci = "tanggal_kunjungan";
        } else if (metode == "Petugas") {
            kata_kunci = "petugas";
        } else if (metode == "Nama") {
            kata_kunci = "nama";
        }
            
            
            String query = "select *, nama from kunjungan LEFT Join pasien ON kunjungan.kode = pasien.kode where " + kata_kunci + " like '%" + txt_kode_kunjungan.getText() + "%'";
            koneksi objkoneksi = new koneksi();
            Connection con = (Connection) koneksi.bukakoneksi();
            Statement stat = (Statement) con.createStatement();
            ResultSet rs = stat.executeQuery(query);
            while (rs.next()) {
                MapTableKunjungan.addRow(new Object[]{rs.getString(1), rs.getString(12), rs.getString(2), rs.getString(3)});
                
            }
            table_kunjungan.setModel(MapTableKunjungan);
        } catch (Exception e) {
            
        }
    }
    
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        combo_kunjungan = new javax.swing.JComboBox();
        txt_kode_kunjungan = new javax.swing.JTextField();
        btn_cari_kunjungan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_kunjungan = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Kunjungan"));

        jLabel9.setText("Tampilkan berdasarkan :");

        combo_kunjungan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kode Pasien", "Nama", "Tanggal Kunjungan", "Petugas" }));

        btn_cari_kunjungan.setText("Tampilkan");
        btn_cari_kunjungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cari_kunjunganActionPerformed(evt);
            }
        });

        table_kunjungan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama", "Tanggal", "Petugas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_kunjungan);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_kunjungan, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_kode_kunjungan, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cari_kunjungan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(combo_kunjungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kode_kunjungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari_kunjungan)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btn_cari_kunjunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cari_kunjunganActionPerformed
// TODO add your handling code here:
    String kode = txt_kode_kunjungan.getText();
    
    if (kode.equals("") || kode.length() < 1) {
        JOptionPane.showMessageDialog(null, "Silahkan isi kata kunci yang akan dicari!", "Message",
                JOptionPane.INFORMATION_MESSAGE);
        txt_kode_kunjungan.requestFocus();
    } else {
        cari_kunjungan();
    }
    
    
}//GEN-LAST:event_btn_cari_kunjunganActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    new Laporan().show();
    this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    bukakunjungan();
}//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataKunjungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataKunjungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataKunjungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataKunjungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DataKunjungan().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari_kunjungan;
    private javax.swing.JComboBox combo_kunjungan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_kunjungan;
    private javax.swing.JTextField txt_kode_kunjungan;
    // End of variables declaration//GEN-END:variables
}
