/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormPeriksa.java
 *
 * Created on May 10, 2013, 8:51:18 PM
 */
package Desktop;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Izani Note-PC1
 */
public class FormPeriksa extends javax.swing.JFrame {

    /** Creates new form FormPeriksa */
    public FormPeriksa() {
        initComponents();
        setTitle("Formulir Periksa PKM-UI");
        bukaobat();
    }
    
    public void bukaobat(){
        DefaultTableModel MapTablePeriksa = new DefaultTableModel();
        MapTablePeriksa.addColumn("Nama Obat");
        MapTablePeriksa.addColumn("Stock");
        
        try {
            String query = "select * from db_obat";
            koneksi objkoneksi = new koneksi();
            Connection con = (Connection) koneksi.bukakoneksi();
            Statement stat = (Statement) con.createStatement();
            ResultSet rs = stat.executeQuery(query);
            while (rs.next()) {
                MapTablePeriksa.addRow(new Object[]{rs.getString(2),rs.getString(4)});
                
            }
            table_obat.setModel(MapTablePeriksa);
        } catch (Exception e) {
            
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kode_periksa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_keluhan = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txta_resep = new javax.swing.JTextArea();
        btn_simpan_periksa = new javax.swing.JButton();
        btn_reset_periksa = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_pemeriksa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_diagnosa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_obat = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Periksa"));

        jLabel1.setText("Kode");

        jLabel2.setText("Keluhan");

        jLabel3.setText("Resep dan");

        txta_keluhan.setColumns(20);
        txta_keluhan.setRows(5);
        jScrollPane1.setViewportView(txta_keluhan);

        txta_resep.setColumns(20);
        txta_resep.setRows(5);
        jScrollPane2.setViewportView(txta_resep);

        btn_simpan_periksa.setText("Simpan dan Kirim");
        btn_simpan_periksa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpan_periksaActionPerformed(evt);
            }
        });

        btn_reset_periksa.setText("Reset");
        btn_reset_periksa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reset_periksaActionPerformed(evt);
            }
        });

        jLabel4.setText("Pemeriksa");

        jLabel5.setText("dr.");

        jLabel6.setText("Diagnosa");

        jLabel7.setText("Keterangan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_reset_periksa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_simpan_periksa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(40, 40, 40)
                                .addComponent(txt_diagnosa, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                    .addComponent(kode_periksa, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                    .addComponent(txt_pemeriksa, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))))))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kode_periksa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_diagnosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pemeriksa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_reset_periksa)
                    .addComponent(btn_simpan_periksa)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resep Obat"));

        table_obat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Obat", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(table_obat);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void kirim(){
        Object[] options = {"Ya", "Batal"};
        if (JOptionPane.showOptionDialog(null, "Anda yakin keluhan dan resep sudah diisi dengan benar?","Warning",
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,null, options, options[0])
                == 0) {
        try {
            koneksi objkoneksi = new koneksi();
            Connection con = (Connection) koneksi.bukakoneksi();
            Statement stmt = (Statement) con.createStatement(
                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
            String query = "insert into periksa values"
                    + "('" + kode_periksa.getText() + "','" + txta_keluhan.getText() + "',"
                    + "'" + txta_resep.getText() + "','" + txt_diagnosa.getText() + "',"
                    + "'" + txt_pemeriksa.getText() + "','" + "','1')";
            int rows = stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "Data telah terkirim", "Message",
                    JOptionPane.INFORMATION_MESSAGE);
            kode_periksa.setText("");
            reset();
            new Apotek().show();
            this.dispose();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    }
      
    public void reset(){
        txta_keluhan.setText("");
        txta_resep.setText("");
        txt_diagnosa.setText("");
        txt_pemeriksa.setText("");
        
    }
    
private void btn_simpan_periksaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpan_periksaActionPerformed
// TODO add your handling code here:
    String kode, keluhan, resep, diagnosa, pemeriksa;
    kode = kode_periksa.getText();
    keluhan = txta_keluhan.getText();
    resep = txta_resep.getText();
    diagnosa = txt_diagnosa.getText();
    pemeriksa = txt_pemeriksa.getText();
    
    try {
        koneksi objkoneksi = new koneksi();
        Connection con = (Connection) koneksi.bukakoneksi();
        
        if (kode.equals("") || kode.length() < 1) {
            JOptionPane.showMessageDialog(null, "Kode Pasien harus diisi!", "Message",
                    JOptionPane.INFORMATION_MESSAGE);
            kode_periksa.requestFocus();
        } else if (kode.length() > 5){
            JOptionPane.showMessageDialog(null,"Kode hanya terdiri dari 5 karakter!", "Message",
                    JOptionPane.INFORMATION_MESSAGE);
            kode_periksa.requestFocus();
        } else if (keluhan.equals("") || keluhan.length() < 1) {
            JOptionPane.showMessageDialog(null, "Keluhan Pasien agar diisi!", "Message",
                    JOptionPane.INFORMATION_MESSAGE);
            txta_keluhan.requestFocus();
        } else if (resep.equals("") || resep.length() < 1) {
            JOptionPane.showMessageDialog(null, "Resep Dokter harus diisi!", "Message",
                    JOptionPane.INFORMATION_MESSAGE);
            txta_resep.requestFocus();
        } else if (diagnosa.equals("") || diagnosa.length() < 1) {
            JOptionPane.showMessageDialog(null, "Diagnosa Dokter harus diisi!", "Message",
                    JOptionPane.INFORMATION_MESSAGE);
            txt_diagnosa.requestFocus();
        } else if (pemeriksa.equals("") || pemeriksa.length() < 1) {
            JOptionPane.showMessageDialog(null, "Nama Dokter harus diisi!", "Message",
                    JOptionPane.INFORMATION_MESSAGE);
            txt_pemeriksa.requestFocus();
        } else {
            kirim();
        }
    } catch (SQLException e) {
        
    }
}//GEN-LAST:event_btn_simpan_periksaActionPerformed

private void btn_reset_periksaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reset_periksaActionPerformed
// TODO add your handling code here:
    reset();
}//GEN-LAST:event_btn_reset_periksaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPeriksa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPeriksa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPeriksa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPeriksa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormPeriksa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reset_periksa;
    private javax.swing.JButton btn_simpan_periksa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField kode_periksa;
    private javax.swing.JTable table_obat;
    private javax.swing.JTextField txt_diagnosa;
    private javax.swing.JTextField txt_pemeriksa;
    private javax.swing.JTextArea txta_keluhan;
    private javax.swing.JTextArea txta_resep;
    // End of variables declaration//GEN-END:variables
}
