/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Kunjungan.java
 *
 * Created on May 10, 2013, 8:39:15 PM
 */
package Desktop;

import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
/**
 *
 * @author Izani Note-PC1
 */
public class Kunjungan extends javax.swing.JFrame {

    /** Creates new form Kunjungan */
    public Kunjungan() {
        initComponents();
        setTitle("Formulir Pengunjung PKM-UI");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_kode_kunjungan = new javax.swing.JTextField();
        txt_tanggal_kunjungan = new javax.swing.JTextField();
        btn_daftar_kunjungan = new javax.swing.JButton();
        btn_utama_kunjungan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_petugas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Kunjungan"));

        jLabel1.setText("Kode");

        jLabel2.setText("Waktu Kunjungan");

        txt_kode_kunjungan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_kode_kunjunganKeyReleased(evt);
            }
        });

        txt_tanggal_kunjungan.setEditable(false);

        btn_daftar_kunjungan.setText("Daftar");
        btn_daftar_kunjungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_daftar_kunjunganActionPerformed(evt);
            }
        });

        btn_utama_kunjungan.setText("Tampilan Utama");
        btn_utama_kunjungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_utama_kunjunganActionPerformed(evt);
            }
        });

        jLabel3.setText("Petugas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_utama_kunjungan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_daftar_kunjungan))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_petugas, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_tanggal_kunjungan)
                                .addComponent(txt_kode_kunjungan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_kode_kunjungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_tanggal_kunjungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txt_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_daftar_kunjungan)
                    .addComponent(btn_utama_kunjungan))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void daftar() {
        try {
            koneksi objkoneksi = new koneksi();
            Connection con = (Connection) koneksi.bukakoneksi();
            Statement stmt = (Statement) con.createStatement (
                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
            String query = "insert into kunjungan values"
                    + "('" + txt_kode_kunjungan.getText() + "','" + txt_tanggal_kunjungan.getText() + "',"
                    + "'" + txt_petugas.getText() + "')";
            int rows = stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "Data telah diterima", "Message",
                    JOptionPane.INFORMATION_MESSAGE);
           new FormPeriksa().show();
            this.dispose();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    
    
    
private void btn_utama_kunjunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_utama_kunjunganActionPerformed
// TODO add your handling code here
    new TampilanUtama().show();
    this.dispose();
}//GEN-LAST:event_btn_utama_kunjunganActionPerformed

private void txt_kode_kunjunganKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kode_kunjunganKeyReleased
// TODO add your handling code here:
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        DecimalFormat dcf = new DecimalFormat("00");
        Calendar now = Calendar.getInstance();
        int hrs = now.get(Calendar.HOUR_OF_DAY);
        int min = now.get(Calendar.MINUTE);
        int sec = now.get(Calendar.SECOND);
        
        txt_tanggal_kunjungan.setText(String.valueOf(df.format(Calendar.getInstance().getTime()) 
                + ", " + dcf.format(hrs) + ":" + dcf.format(min)));
}//GEN-LAST:event_txt_kode_kunjunganKeyReleased

private void btn_daftar_kunjunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_daftar_kunjunganActionPerformed
// TODO add your handling code here:
    String kode, kunjungan, petugas;
    kode = txt_kode_kunjungan.getText();
    petugas = txt_petugas.getText();
    
    try {
        koneksi objkoneksi = new koneksi();
        Connection con = (Connection) koneksi.bukakoneksi();
        
        if (kode.equals("") || kode.length() < 1) {
            JOptionPane.showMessageDialog(null, "Kode Pasien Harus Diisi!", "Warning",
                    JOptionPane.INFORMATION_MESSAGE);
            txt_kode_kunjungan.requestFocus();
        } else if (kode.length() > 5){
            JOptionPane.showMessageDialog(null,"Kode hanya terdiri dari 5 karakter!", "Message",
                    JOptionPane.INFORMATION_MESSAGE);
            txt_kode_kunjungan.requestFocus();
        } else if (petugas.equals("") || petugas.length() < 1) {
            JOptionPane.showMessageDialog(null, "Nama Petugas Harus Diisi!", "Warning",
                    JOptionPane.INFORMATION_MESSAGE);
            txt_petugas.requestFocus();
        } else {
            daftar();
        }
    } catch (SQLException e) {
        
    }
}//GEN-LAST:event_btn_daftar_kunjunganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kunjungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kunjungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kunjungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kunjungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Kunjungan().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_daftar_kunjungan;
    private javax.swing.JButton btn_utama_kunjungan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_kode_kunjungan;
    private javax.swing.JTextField txt_petugas;
    private javax.swing.JTextField txt_tanggal_kunjungan;
    // End of variables declaration//GEN-END:variables
}
